packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  date-fns: ^4.1.0
  dotenv-cli: ^8.0.0
  eslint: ^9.33.0
  next: ^15.2.3
  prettier: ^3.6.2
  prisma: ^6.13.0
  "@prisma/client": ^6.13.0
  superjson: ^2.2.2
  tailwindcss: ^4.1.12
  typescript: ^5.8.3
  zod: ^4.0.17
  "@tanstack/react-query": ^5.85.3
  "@trpc/client": ^11.0.0
  "@trpc/react-query": ^11.0.0
  "@trpc/tanstack-react-query": ^11.0.0
  "@trpc/server": ^11.0.0
  "@types/node": ^22.13.14
catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.10
    "@types/react-dom": ^19.1.9
nodeLinker: hoisted
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - aws-sdk
  - prisma
  - sharp
  - unrs-resolver
