packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  date-fns: ^4.1.0
  dotenv-cli: ^11.0.0
  eslint: ^9.39.1
  next: ^16.0.3
  prettier: ^3.6.2
  prisma: ^6.19.0
  "@prisma/client": ^6.19.0
  superjson: ^2.2.5
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  zod: ^4.1.12
  "@tanstack/react-query": ^5.90.9
  "@trpc/client": ^11.7.1
  "@trpc/react-query": ^11.7.1
  "@trpc/tanstack-react-query": ^11.7.1
  "@trpc/server": ^11.7.1
  "@types/node": ^24.10.1
catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": 19.1.10
    "@types/react-dom": ^19.2.3
nodeLinker: hoisted
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - aws-sdk
  - prisma
  - sharp
  - unrs-resolver
